### ISSUE TITLE
6th component of an ARN is required (ECR)

### ISSUE THREAD

**Issue by stevebanik** [aws-samples/aws-cdk-examples#821] opened 2023-03-24 13:35 UTC
### Describe the bug

In this file, line 23:

https://github.com/aws-samples/aws-cdk-examples/blob/master/python/lambda-from-container/app.py

if 'use_pre_existing_image = True' rather than 'use_pre_existing_image = False' the following error appears:

```jsii.errors.JavaScriptError: 
  Error: The `resource` component (6th component) of an ARN is required: arn:aws:ecr:${Token[AWS.Region.7]}:${Token[AWS.AccountId.3]}
      at parseArnShape (/private/var/folders/td/89g45s_d64z_l75m5ksgnf840000gq/T/jsii-kernel-knKSjH/node_modules/aws-cdk-lib/core/lib/arn.js:1:5729)
      at Arn.split (/private/var/folders/td/89g45s_d64z_l75m5ksgnf840000gq/T/jsii-kernel-knKSjH/node_modules/aws-cdk-lib/core/lib/arn.js:1:2317)
      at Stack.splitArn (/private/var/folders/td/89g45s_d64z_l75m5ksgnf840000gq/T/jsii-kernel-knKSjH/node_modules/aws-cdk-lib/core/lib/stack.js:1:8334)
      at Import.repositoryUriWithSuffix (/private/var/folders/td/89g45s_d64z_l75m5ksgnf840000gq/T/jsii-kernel-knKSjH/node_modules/aws-cdk-lib/aws-ecr/lib/repository.js:1:1024)
      at Import.repositoryUriForTag (/private/var/folders/td/89g45s_d64z_l75m5ksgnf840000gq/T/jsii-kernel-knKSjH/node_modules/aws-cdk-lib/aws-ecr/lib/repository.js:1:649)
      at Import.repositoryUriForTagOrDigest (/private/var/folders/td/89g45s_d64z_l75m5ksgnf840000gq/T/jsii-kernel-knKSjH/node_modules/aws-cdk-lib/aws-ecr/lib/repository.js:1:936)
      at EcrImageCode.bind (/private/var/folders/td/89g45s_d64z_l75m5ksgnf840000gq/T/jsii-kernel-knKSjH/node_modules/aws-cdk-lib/aws-lambda/lib/code.js:1:7887)
      at new Function (/private/var/folders/td/89g45s_d64z_l75m5ksgnf840000gq/T/jsii-kernel-knKSjH/node_modules/aws-cdk-lib/aws-lambda/lib/function.js:1:2829)
      at Kernel._create (/private/var/folders/td/89g45s_d64z_l75m5ksgnf840000gq/T/tmpjgllvvnv/lib/program.js:9959:29)
      at Kernel.create (/private/var/folders/td/89g45s_d64z_l75m5ksgnf840000gq/T/tmpjgllvvnv/lib/program.js:9688:29)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/user/Documents/churchill-downs/twinspires-sandbox/ahead/bdsproducts-purge-and-archive/app.py", line 89, in <module>
    LambdaBdsProductsPurgeAndArchiveStack(
  File "/opt/homebrew/lib/python3.11/site-packages/jsii/_runtime.py", line 112, in __call__
    inst = super().__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Documents/churchill-downs/twinspires-sandbox/ahead/bdsproducts-purge-and-archive/app.py", line 64, in __init__
    aws_lambda.Function(self,
  File "/opt/homebrew/lib/python3.11/site-packages/jsii/_runtime.py", line 112, in __call__
    inst = super().__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/aws_cdk/aws_lambda/__init__.py", line 23715, in __init__
    jsii.create(self.__class__, self, [scope, id, props])
  File "/opt/homebrew/lib/python3.11/site-packages/jsii/_kernel/__init__.py", line 334, in create
    response = self.provider.create(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/jsii/_kernel/providers/process.py", line 362, in create
    return self._process.send(request, CreateResponse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/jsii/_kernel/providers/process.py", line 339, in send
    raise RuntimeError(resp.error) from JavaScriptError(resp.stack)
RuntimeError: The `resource` component (6th component) of an ARN is required: arn:aws:ecr:${Token[AWS.Region.7]}:${Token[AWS.AccountId.3]}```

### Expected Behavior

I expected line 27 to execute without errors

### Current Behavior

See stacktrace above

### Reproduction Steps

See notes above

### Possible Solution

ref https://github.com/aws-samples/aws-cdk-examples/issues/715

### Additional Information/Context

_No response_

### CDK CLI Version

2.70.0 (build c13a0f1)

### Framework Version

_No response_

### Node.js Version

v19.8.1

### OS

ProductName:    macOS ProductVersion: 12.6.3 BuildVersion:   21G419

### Language

Python

### Language Version

Python (3.11.2)

**Comment by peterwoodworth** [comment] 2023-03-24 17:56
Thanks @stevebanik, we're tracking this in #715, so I'll close this as a duplicate of that

**Closed by peterwoodworth** 2023-03-24 17:56 UTC
Labels: bug, needs-triage
