### ISSUE TITLE
503 ALB error

### ISSUE THREAD

**Issue by josjaf** [aws-samples/aws-cdk-examples#148] opened 2019-10-29 03:42 UTC
### What is the problem?
Load Balancer 503
-->
The stack deploys - I think this line needs to be 80 instead of 8080

**Comment by sankeyraut** [comment] 2019-11-04 17:16
I tried deploying the ALB stack. Gives 503. Are we updating this one ?

**Comment by josjaf** [comment] 2019-11-04 17:17
I have the fix - I'll send a PR.

**Comment by sankeyraut** [comment] 2019-11-04 17:19
Can you mention here what is the fix ? Will try and test it

**Comment by NGL321** [comment] 2019-11-14 01:25
Hi @josjaf,

Did you happen to get a chance to put together a fix for this? If not, I'd be happy to look into it.

Let me know!
😸

**Comment by SomayaB** [comment] 2019-12-18 22:49
Hi @josjaf, do you have any updates on this?

**Comment by NGL321** [comment] 2019-12-19 19:33
Unable to reproduce.

Closing due to inactivity.

**Closed by NGL321** 2019-12-19 19:33 UTC
Labels: bug, p1, status/in-progress, status/needs-repro

**Comment by josjaf** [comment] 2019-12-19 19:41
It happened to me once or twice, I couldnt reproduce it.
