### ISSUE TITLE
api-cors-lambda-crud-dynamodb POST timeout

### ISSUE THREAD

**Issue by DavidQN** [aws-samples/aws-cdk-examples#195] opened 2019-11-29 15:50 UTC
### What is the problem?

I believe this could also fall into `Guidance`.

Specifically for: `typescript`/`api-cors-lambda-crud-dynamodb` example code, after building and deploying the stack. If you try to run the `POST` request you get a timeout (3 seconds). 

This is done using an example body such as:
```json
{
    "body":{
        "temp": "hello!!"
    }
}

``` 
- All other methods in this example code seem to work exactly as expected, except for `create`.
- If I run this locally and call the `create.js` from my machine, inserting into dynamodb seems to work fine.  So the code isn't the issue since the ENV variables are correct.  
- This lead me to believe that perhaps this has something to do with permissions on the create lambda? Since there is a timeout, which I believe occurs on the connection to the dynamodb table on line 23: `await db.put(params).promise();` since no error is ever outputted and just a timeout.
- I checked the cloudformation output, but they all seem to be correct:
    - Correct ServiceRole: "lambda.amazonaws.com"
![image](https://user-images.githubusercontent.com/23644019/69878806-eafa8300-1293-11ea-9cd4-5a6192311dbc.png)

    - Correct Policies for DynamoDb attached to said service role
![image](https://user-images.githubusercontent.com/23644019/69879293-0ade7680-1295-11ea-8134-7276d2e20e1d.png)

- All attached to the lambda in question
![image](https://user-images.githubusercontent.com/23644019/69879030-6c521580-1294-11ea-9c1f-fff74c9e489e.png)

### Reproduction Steps
- cd into `typescript/api-cors-lambda-crud-dynamodb/`
- npm install
- cdk deploy
- Go to Apigateway and in POST  /items place this body
```json
{
    "body":{
        "temp": "hello!!"
    }
}
``` 

### Verbose Log

- Response: 
![image](https://user-images.githubusercontent.com/23644019/69879634-f0f16380-1295-11ea-80f7-c14f553b3a5a.png)

### Environment

  - **CDK CLI Version: 1.16.2 ** 
  - **Example: api-cors-lambda-crud-dynamodb ** 
  - **Example Version:  ** 
  - **OS: Windows ** 
  - **Language: Typescript ** 

Exact same environment as the example code

**Comment by rhboyd** [comment] 2019-11-29 15:59
does every POST fail, or just the first?

**Comment by DavidQN** [comment] 2019-11-29 17:42
Every POST fails. This doesn't seem to be a lambda warmup issue if that is what you were getting at.

**Comment by mgijsbertihodenpijl** [comment] 2019-12-10 10:09
I had exactly the same issue. I just followed the instructions from the readme.
In the CloudWatch logs the following error was reported:
`2019-12-10T10:02:18.623Z	undefined	ERROR	Uncaught Exception	
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'uuid/v4'",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'uuid/v4'",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:45:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",
        "    at Module.load (internal/modules/cjs/loader.js:653:32)",
        "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
        "    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)",
        "    at startup (internal/bootstrap/node.js:283:19)"
    ]
}
`

**Comment by DavidQN** [comment] 2019-12-11 02:21
I apologize, I forgot to follow up on this. @mgijsbertihodenpijl thank you for your response, I ended up resolving this earlier, but it was still rather embarrassing on my end. 

The above error displayed above wouldn't even display in the cloudwatch logs until I made a few changes as it would still display the timeout.

Lambdas on CDK default to 3 seconds with the memory size of 104. It seems like this also includes the "Integration Latency", which I wasn't aware of. Increasing the timeout to 10 seconds should allow the actual error to appear on both the console/cloudwatch.

**Comment by elderapo** [comment] 2020-01-23 23:35
I think the problem is that there is no `uuid` library in `package.json` and on top of that `node_modules` does not get uploaded to the lambda.

**Comment by StraightOuttaCrompton** [comment] 2020-02-11 20:42
```aws-sdk``` is also not in ```package.json``` but is required by the files in ```src```. How are these dependencies being resolved in the lambdas?

**Comment by lukepushlabs** [comment] 2020-02-12 23:33
@elderapo What's the solution to that then? Should each handler I create have its own node_modules folder?

**Comment by elderapo** [comment] 2020-02-13 03:09
@StraightOuttaCrompton I am not sure but maybe `aws-sdk` should be installed globally in your environment (I think it's always installed in AWS lambda).

@lukepushlabs You can use [ncc](https://github.com/zeit/ncc), `webpck` or any other bundler to create a bundle for each lambda (`ncc` will only pick dependencies from `node_modes` that are used by your lambda). This way your lambdas will be as lightweight as possible.

**Comment by oscarnevarezleal** [comment] 2020-03-03 15:37
I think the author tried to separate the logic across multiple handlers so he could benefit from shared [layers ](https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html)(`node_modules`). 

Slt


```
// This works when layerDirectory is a path that contains this structure : `nodejs/node_modules`
const nodeModulesLayer = new lambda.LayerVersion(this, 'NodeModulesLayer',
      {
        code: lambda.AssetCode.fromAsset(layerDirectory),
        compatibleRuntimes: [lambda.Runtime.NODEJS_10_X]
      }
    );

// ......

    const createOne = new lambda.Function(this, 'createPetFcn', {
      code: new lambda.AssetCode('src'),
      handler: 'create.handler',
      layers: [nodeModulesLayer], // <<< here
      runtime: lambda.Runtime.NODEJS_10_X,
      environment: {
        TABLE_NAME: dynamoTable.tableName,
        PRIMARY_KEY: 'petId'
      }
    });
```

**Comment by YannHulot** [comment] 2020-03-05 02:13
I can confirm that I a having this issue as well. The POST call fails because the uuid dependency is not available at runtime. How can this be?

**Comment by marcindulak** [comment] 2020-03-17 01:28
> I can confirm that I a having this issue as well. The POST call fails because the uuid dependency is not available at runtime. How can this be?

`src/package.json` is missing? A problem like that has been discussed in an old thread https://github.com/aws-samples/aws-cdk-examples/issues/110#issuecomment-550506116

**Comment by oscarnevarezleal** [comment] 2020-04-09 05:19
I have a working demo [here](https://github.com/oscarnevarezleal/api-cors-lambda-crud-dynamodb) , take a look 👍

**Closed** 2021-07-10 00:18 UTC
Labels: bug, guidance, language/typescript, needs-reproduction, p2
