### ISSUE TITLE
typescript - api-cors-lambda-crud-dynamodb  -missing uuid in package.json

### ISSUE THREAD

**Issue by nazreen** [aws-samples/aws-cdk-examples#276] opened 2020-04-23 14:47 UTC
### What is the problem?
Error message `Error: Cannot find module 'uuid/v4` when testing `create` function.

### Reproduction Steps
1. deploy the stack as per instructions
2. go to the AWS Console and test `createItem` function with the following test event:

```
{
  "body": "{\"data\":{\"name\":\"foo\"}}"
}
```

3. The result will be that the task timed out. Go to Cloudwatch and view the log for the function. It will complain this: `"Error: Cannot find module 'uuid/v4`

### Environment

  - **CDK CLI Version:** 1.34.1
  - **Example:** api-cors-lambda-crud-dynamodb
  - **Example Version:** createItem function
  - **OS:**  OSX Catalina
  - **Language:** Typescript

### Other information 
The solution requires the uuid package being present inside a `node_modules` of the `src` folder. Currently there is no package.json inside the src folder.

**Comment by hossain-rayhan** [comment] 2020-04-23 19:09
Hi @nazreen , thanks for creating the issue. I was able to reproduce it. Will update once I finish testing your PR.

**Comment by nazreen** [comment] 2020-04-23 21:44
hi @hossain-rayhan , I realised my PR was wrong. I am going to update it now.

**Comment by nazreen** [comment] 2020-04-23 22:17
@hossain-rayhan I have updated the issue description with more detail on the error and the solution. I will submit a PR with the fix now.

**Comment by nazreen** [comment] 2020-04-23 22:19
ok so the fix to this issue is in #278

**Comment by NGL321** [comment] 2020-05-08 00:50
Hey @nazreen, I apologize for the delay in response!

It appears that the issue is not the `package.json` but that the `uuid` package actually introduced a [breaking change](https://www.npmjs.com/package/uuid#deep-requires-now-deprecated) to the way it handles imports. You can see the issue was also experienced with just [lambda](https://stackoverflow.com/questions/60610487/aws-lambda-error-cannot-find-module-uuid-v4).

Thank you for working on this!

😷

**Comment by nazreen** [comment] 2020-05-08 01:41
@NGL321 , 

ok, so I tried updating the line to:
`const { v4: uuidv4 } = require('uuid');` per the latest instruction from the npm page, the new error is `"Error: Cannot find module 'uuid'"`

correct me if I'm wrong, but `uuid` is not a built-in node module, so it has to be installed via npm anyways right?

**Comment by NGL321** [comment] 2020-05-08 02:21
@nazreen After verification, you are correct. Actually, in hindsight, I am surprised this worked to begin with 🤷.

The proper solution to this would be to utilize a [Lambda Layer](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-readme.html#layers), however the solution proposed [here](https://github.com/aws-samples/aws-cdk-examples/issues/261#issuecomment-604604186) of zipping the whole lambda with dependencies as a single [deployment package](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-package.html) is also valid.

There are really two options for this. Either pre-package and update the example with that package, or add instructions on building out that package.
I understand this is more work than you initially signed up for, but if you still want to add this, please feel free to @ me in another PR!

Cheers
😸 😷

**Comment by nazreen** [comment] 2020-05-08 03:02
@NGL321 thanks for the quick response! Going to write this now before I go to bed (will continue tomorrow). I'd like to see this through, don't worry!

Okay, so the deployment package approach, is the approach in this PR. AFAIK, cdk's `lambda.AssetCode()` will bundle the specified directory. All its contents will be uploaded as the lambda code, in this case, including the `node_modules` folder.

However, I think there's a complication that you might be able to shed light on. The build fails. The error message is `--app is required either in command-line, in cdk.json or in ~/.cdk.json`

I think this is because for every `package.json`, there's a check for an adjacent `cdk.json`. So since the `package.json` inside `src` doesn't, the error throws. Is this accurate? I'm not sure, just a guess.

**Comment by nazreen** [comment] 2020-05-13 13:26
@NGL321 bump :) just checking if you're aware of this

**Comment by stilren** [comment] 2020-06-30 18:07
Anyway we could get a fix for this? Would be good with an example showing how to do external dependencies with ts cdk

**Comment by sachin10101998** [comment] 2020-09-05 20:22
Any fix available for this yet?

**Comment by bbarthel** [comment] 2020-09-07 20:58
A easy fix is to use 
const crypto = require('crypto');
item[PRIMARY_KEY] = crypto.randomBytes(16).toString("hex");

**Comment by chrischenyc** [comment] 2021-02-27 05:39
I think using the experimental [@aws-cdk/aws-lambda-nodejs](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-nodejs-readme.html) is the way to go, works for me:

https://github.com/chrischenyc/url-shortener-cdk-typescript

**Closed** 2021-07-10 00:18 UTC
Labels: bug, dependencies, effort/medium, in-progress, language/typescript, p1
